In [2]:
import pandas as pd
import numpy as np

# Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [3]:
#Alexandre Theophile Vandermode
#creating a matrix using Vandermode method
Matrix= np.array([1,2,3,4,5])
n= 4
vander = np.vander(Matrix,n, increasing= False)
vander_a = np.vander(Matrix,n, increasing= True)
print("\n A array:", Matrix, "\n")
print("\n Number of columns in output matrix should be: 4")
print("\n Vander matrix of the input array in decreasing order of powers:\n", vander)
print("\n Vander matrix of the input array in Increasing order of powers:\n", vander_a)




 A array: [1 2 3 4 5] 


 Number of columns in output matrix should be: 4

 Vander matrix of the input array in decreasing order of powers:
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Vander matrix of the input array in Increasing order of powers:
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


In [4]:
#creating a matrix by using column stack method
a= np.array([1,2,3,4,5])
Y= 3
output= np.column_stack([a**(Y-1-i) for i in range(Y)])
print("\n A Array:", a)
print("\n Number of column in a array:", Y)
print("\n Output of the column_stack array in decreasing oder of powers:\n", output)


 A Array: [1 2 3 4 5]

 Number of column in a array: 3

 Output of the column_stack array in decreasing oder of powers:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


# Problem Statement 2: 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [17]:
#Finding Moving Average
def moving_average(a, n=3):
    cumsum= np.cumsum(a, dtype = float)
    cumsum[n:]= cumsum[n:]-cumsum[:-n]
    return cumsum[n-1:]/n
a= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

print('\n Data for moving average:', a)
print("\n cumulative sum of data:", cumsum)
print("\n moving average:", moving_average(a, n=3))


 Data for moving average: [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

 cumulative sum of data: [  3   8  15  14  17  20  29  86 148 218 252 280 349]

 moving average: [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
